site_name: My Computers Noteski

#theme:
 # name: 'material'
site_name: MkDocs
#site_description: Project documentation with Markdown.
#site_author: MkDocs Team

repo_url: https://github.com/veedar/noteski/
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - User Guide:
        - Writing Your Docs: user-guide/writing-your-docs.md
        - Styling Your Docs: user-guide/styling-your-docs.md
        - Configuration: user-guide/configuration.md
        - Deploying Your Docs: user-guide/deploying-your-docs.md
        - Custom Themes: user-guide/custom-themes.md
        - Plugins: user-guide/plugins.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: veedar
        repo: noteski


plugins:
    - search
