site_name: Noteski
#theme:
 #   name: mkdocs
  #  highlightjs: true
   # hljs_languages:
    #    - yaml
     #   - django

plugins:
    - search
    
nav:
- Home: 'index.md'
- Reconnaissance
- Scanning
- Exploitation
- Maintaining access
- Covering Tracks
- Reporting
- Tools:
    - 'Writing your docs': 'writing-your-docs.md'
    - 'Styling your docs': 'styling-your-docs.md'
- About: 'about.md'
