site_name: Noteski
#theme:
 #   name: mkdocs
  #  highlightjs: true
   # hljs_languages:
    #    - yaml
     #   - django

plugins:
    - search
    
nav:
- Home: 'index.md'
- Scanning: 'scanning.md'
- Exploitation: 'exploitation.md'
- Tools:
    - 'Nmap': 'tools/nmap.md'
    - 'Metasploit': 'tools/metasploit.md'
- About: 'about.md'
